# Generated by Django 6.0.2 on 2026-03-06 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_packages_center'),
        ('pay', '0001_initial'),
        ('yogui', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='packages.packages'),
        ),
        migrations.AddField(
            model_name='pay',
            name='yogui',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yogui.yogui'),
        ),
    ]
