# Generated by Django 6.0.2 on 2026-02-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YogaCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('capacity', models.PositiveIntegerField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='static/img/')),
                ('description', models.TextField()),
                ('at_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
