# Generated by Django 6.0.2 on 2026-02-24 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centeryoga', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yogacenter',
            name='capacity',
        ),
        migrations.AddField(
            model_name='yogacenter',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='yogacenter',
            name='hours_of_operation',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
