# Generated by Django 6.0.2 on 2026-03-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centeryoga', '0002_remove_yogacenter_capacity_yogacenter_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yogacenter',
            name='capacity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
