# Generated by Django 6.0.2 on 2026-03-04 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pay', '0001_initial'),
        ('rules', '0002_rules_at_update_rules_operator_rules_type_rule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RulePay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pay.pay')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.rules')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('pay', 'rule'), name='unique_rule_pay')],
            },
        ),
    ]
