# Generated by Django 6.0.2 on 2026-03-06 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('yogui', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('at_creation', models.DateTimeField(auto_now_add=True)),
                ('at_update', models.DateTimeField(auto_now=True)),
                ('yogui', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yogui.yogui')),
            ],
        ),
    ]
