# Generated by Django 6.0.2 on 2026-02-14 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogui', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yogui',
            name='id_card',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
