# Generated by Django 6.0.2 on 2026-03-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogui', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yogui',
            name='is_suscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='yogui',
            name='id_card',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
