# Generated by Django 6.0.2 on 2026-02-23 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centeryoga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RulesCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('at_creation', models.DateTimeField(auto_now_add=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='centeryoga.yogacenter')),
            ],
        ),
    ]
