# Generated by Django 6.0.2 on 2026-02-16 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centeryoga', '0001_initial'),
        ('rules_center', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='center',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='centeryoga.yogacenter'),
            preserve_default=False,
        ),
    ]
