# Generated by Django 6.0.2 on 2026-02-22 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules_center', '0002_rule_center'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='action',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='action_target',
        ),
    ]
