# Generated by Django 6.0.2 on 2026-02-23 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rules_center', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.IntegerField()),
                ('at_creation', models.DateTimeField(auto_now_add=True)),
                ('at_update', models.DateTimeField(auto_now=True)),
                ('rule_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules_center.rulescenter')),
            ],
        ),
    ]
