# Generated by Django 6.0.2 on 2026-02-24 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.JSONField()),
                ('level_package', models.CharField(choices=[('beginner', 'beginner'), ('intermediate', 'intermediate'), ('advanced', 'advanced')], default='beginner', max_length=20)),
                ('category', models.CharField(choices=[('monthly', 'monthly'), ('yearly', 'yearly'), ('single', 'single')], default='monthly', max_length=20)),
                ('stackclass', models.CharField(choices=[('suscription', '999'), ('packages', '10'), ('class', '1')], default='class', max_length=20)),
                ('at_creation', models.DateTimeField(auto_now_add=True)),
                ('at_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
