# Generated by Django 6.0.2 on 2026-02-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_creation', models.DateTimeField(auto_now_add=True)),
                ('especiality', models.CharField(max_length=100)),
                ('photo_profile', models.ImageField(blank=True, null=True, upload_to='instructor_photos/')),
                ('description', models.TextField()),
            ],
        ),
    ]
