# Generated by Django 6.0.2 on 2026-02-23 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centeryoga', '0001_initial'),
        ('instructor', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='yogacenter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='centeryoga.yogacenter'),
            preserve_default=False,
        ),
    ]
