# Generated by Django 6.0.2 on 2026-03-04 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centeryoga', '0003_yogacenter_capacity'),
        ('instructor', '0003_instructor_yogacenter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassYoga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('schedules', models.JSONField()),
                ('photo', models.ImageField(upload_to='classyoga')),
                ('at_creation', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(max_length=100)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centeryoga.yogacenter')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.instructor')),
            ],
        ),
    ]
