# Generated by Django 6.0.2 on 2026-03-06 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classyoga', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classyoga',
            name='capacity_class',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
