# Generated by Django 6.0.2 on 2026-03-04 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classyoga', '0001_initial'),
        ('yogui', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassYogui',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_creation', models.DateTimeField(auto_now_add=True)),
                ('class_yoga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classyoga.classyoga')),
                ('yogui', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yogui.yogui')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('class_yoga', 'yogui'), name='unique_class_yogui')],
            },
        ),
    ]
