# Generated by Django 6.0.2 on 2026-02-23 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rules_center', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RulesPackages',
            fields=[
                ('rulescenter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rules_center.rulescenter')),
                ('promotion_porcentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('access_duration', models.PositiveIntegerField(help_text='Duration in days')),
                ('rules_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules_packages', to='rules_center.rulescenter')),
            ],
            bases=('rules_center.rulescenter',),
        ),
    ]
