# Generated by Django 6.0.2 on 2026-02-16 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules_packages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rulespackages',
            old_name='promotion_percentage',
            new_name='promotion_porcentage',
        ),
    ]
