# Generated by Django 6.0.2 on 2026-02-16 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules_packages', '0002_rename_promotion_percentage_rulespackages_promotion_porcentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rulespackages',
            name='statud',
        ),
    ]
