# Generated by Django 6.0.2 on 2026-03-03 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('access_days', models.JSONField()),
                ('access_time', models.JSONField()),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('at_creation', models.DateTimeField(auto_now_add=True)),
                ('at_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
