# Generated by Django 6.0.2 on 2026-03-04 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centeryoga', '0003_yogacenter_capacity'),
        ('promotion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='center',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='centeryoga.yogacenter'),
            preserve_default=False,
        ),
    ]
