# Generated by Django 6.0.2 on 2026-03-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0003_promotion_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='discount_type',
            field=models.CharField(default='porcentaje', max_length=50),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='access_days',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='access_time',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
