# Generated by Django 6.0.2 on 2026-02-15 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rules_center', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RulesPayment',
            fields=[
                ('rule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rules_center.rule')),
                ('discoint_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('comission_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('statud', models.BooleanField(default=True)),
                ('rules_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules_payment', to='rules_center.rule')),
            ],
            bases=('rules_center.rule',),
        ),
    ]
