# Generated by Django 6.0.2 on 2026-02-16 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules_payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rulespayment',
            old_name='discoint_percentage',
            new_name='discoint_porcentage',
        ),
    ]
