# Generated by Django 6.0.2 on 2026-02-16 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules_payments', '0002_rename_discoint_percentage_rulespayment_discoint_porcentage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rulespayment',
            old_name='comission_percentage',
            new_name='comission_porcentage',
        ),
    ]
