# Generated by Django 6.0.2 on 2026-02-22 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules_payments', '0003_rename_comission_percentage_rulespayment_comission_porcentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rulespayment',
            name='statud',
        ),
    ]
