# Generated by Django 6.0.2 on 2026-02-12 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userYC', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
