# Generated by Django 6.0.2 on 2026-03-06 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('packagessubscription', '0001_initial'),
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagesubscription',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.subscription'),
        ),
        migrations.AddConstraint(
            model_name='packagesubscription',
            constraint=models.UniqueConstraint(fields=('package', 'subscription'), name='unique_package_subscription'),
        ),
    ]
