# Generated by Django 6.0.2 on 2026-02-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CenterAdministrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active_profile', models.BooleanField(default=False)),
                ('at_creation', models.DateTimeField(auto_now_add=True)),
                ('photo_profile', models.ImageField(blank=True, null=True, upload_to='admin_photos/')),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('experience_years', models.PositiveIntegerField(blank=True, null=True)),
                ('statement', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
