# Generated by Django 6.0.2 on 2026-02-15 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center_administration', '0001_initial'),
        ('centeryoga', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='centeradministrator',
            name='yoga_center',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='centeryoga.yogacenter'),
            preserve_default=False,
        ),
    ]
