# Generated by Django 6.0.2 on 2026-02-23 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('center_administration', '0001_initial'),
        ('centeryoga', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='centeradministrator',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='centeradministrator',
            name='yoga_center',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='centeryoga.yogacenter'),
        ),
    ]
