# Generated by Django 6.0.2 on 2026-03-02 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('center_administration', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centeradministrator',
            name='statement',
        ),
    ]
