# Generated by Django 6.0.2 on 2026-02-16 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center_administration', '0002_centeradministrator_yoga_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='centeradministrator',
            name='is_active_profile',
            field=models.BooleanField(default=False),
        ),
    ]
