# Generated by Django 6.0.2 on 2026-03-04 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center_administration', '0003_remove_centeradministrator_statement'),
    ]

    operations = [
        migrations.AddField(
            model_name='centeradministrator',
            name='welcome_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
