# Generated by Django 6.0.2 on 2026-02-23 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center_administration', '0003_centeradministrator_is_active_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='centeradministrator',
            name='experience_years',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='centeradministrator',
            name='photo_profile',
            field=models.ImageField(blank=True, null=True, upload_to='admin_photos/'),
        ),
        migrations.AddField(
            model_name='centeradministrator',
            name='role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='centeradministrator',
            name='statement',
            field=models.TextField(blank=True, null=True),
        ),
    ]
