# Generated by Django 6.0.2 on 2026-03-03 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_refundable', models.BooleanField(default=False)),
                ('is_transferable', models.BooleanField(default=False)),
                ('is_discountable', models.BooleanField(default=False)),
                ('is_acumulative', models.BooleanField(default=False)),
                ('is_active_suspension', models.BooleanField(default=False)),
                ('at_creation', models.DateTimeField(auto_now_add=True)),
                ('at_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
