# Generated by Django 6.0.2 on 2026-02-24 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rules',
            name='at_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='rules',
            name='operator',
            field=models.CharField(choices=[('+', '+'), ('-', '-'), ('*', '*'), ('/', '/'), ('%', '%')], default='+', max_length=10),
        ),
        migrations.AddField(
            model_name='rules',
            name='type_rule',
            field=models.CharField(choices=[('discount', 'discount'), ('refund', 'refund'), ('surcharge', 'surcharge'), ('fine', 'fine')], default='discount', max_length=10),
        ),
        migrations.AddField(
            model_name='rules',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
