# Generated by Django 6.0.2 on 2026-03-06 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pay', '0002_pay_package_pay_yogui'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('client_name', models.CharField(max_length=150)),
                ('client_document', models.CharField(max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('issued', 'Emitida'), ('voided', 'Anulada')], default='issued', max_length=20)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('invoice_file', models.FileField(blank=True, null=True, upload_to='invoices/')),
                ('pay', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='pay.pay')),
            ],
        ),
    ]
